name: CodexIPhone
options:
  deploymentTarget:
    iOS: 17.0
settings:
  base:
    SWIFT_VERSION: 5.0
targets:
  CodexIPhoneApp:
    type: application
    platform: iOS
    sources:
      - CodexIPhoneApp/Sources
      - path: CodexIPhoneApp/Resources
        buildPhase: resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.carl.codexiphone
        PRODUCT_NAME: CodexIPhone
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: G836GGPF7C
        TARGETED_DEVICE_FAMILY: 1
        MARKETING_VERSION: 1.0.3
        CURRENT_PROJECT_VERSION: 2026030101
        INFOPLIST_FILE: Config/AppInfo.plist
        GENERATE_INFOPLIST_FILE: NO
  CodexIPhoneUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - CodexIPhoneUITests
      - path: CodexIPhoneUITests/Resources
        buildPhase: resources
    dependencies:
      - target: CodexIPhoneApp
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.carl.codexiphone.uitests
        PRODUCT_NAME: CodexIPhoneUITests
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: G836GGPF7C
        GENERATE_INFOPLIST_FILE: YES
schemes:
  CodexIPhoneApp:
    build:
      targets:
        CodexIPhoneApp: all
    test:
      targets:
        - CodexIPhoneUITests
    run:
      config: Debug
