name: CodexControlPlaneIPhone
options:
  deploymentTarget:
    iOS: 17.0
settings:
  base:
    SWIFT_VERSION: 5.0
targets:
  CodexControlPlaneApp:
    type: application
    platform: iOS
    sources:
      - CodexControlPlaneApp/Sources
      - path: CodexControlPlaneApp/Resources
        buildPhase: resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.yourorg.codexrelay.controlplane
        PRODUCT_NAME: CodexControlPlane
        CODE_SIGN_STYLE: Automatic
        TARGETED_DEVICE_FAMILY: 1
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        INFOPLIST_KEY_CFBundleDisplayName: CodexCP
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchStoryboardName: LaunchScreen
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone:
          - UIInterfaceOrientationPortrait
        GENERATE_INFOPLIST_FILE: YES
schemes:
  CodexControlPlaneApp:
    build:
      targets:
        CodexControlPlaneApp: all
    run:
      config: Debug
